// This file is auto-generated by @hey-api/openapi-ts

export { getIdentifiers, getInfo, type Options } from './sdk.gen';
export type { ClientOptions, GearImei, GearLabel, GetIdentifiersData, GetIdentifiersErrors, GetIdentifiersResponse, GetIdentifiersResponses, GetInfoData, GetInfoErrors, GetInfoResponse, GetInfoResponses, RefreshIdentifiers, RefreshInfo } from './types.gen';
