// Package serverpublic provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package serverpublic

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/gofiber/fiber/v2"
)

// Defines values for GearCertificationAuthority.
const (
	Ccc      GearCertificationAuthority = "ccc"
	Ce       GearCertificationAuthority = "ce"
	Fcc      GearCertificationAuthority = "fcc"
	Internal GearCertificationAuthority = "internal"
	Miit     GearCertificationAuthority = "miit"
	Rohs     GearCertificationAuthority = "rohs"
	Srrc     GearCertificationAuthority = "srrc"
	Unknown  GearCertificationAuthority = "unknown"
)

// Valid indicates whether the value is a known member of the GearCertificationAuthority enum.
func (e GearCertificationAuthority) Valid() bool {
	switch e {
	case Ccc:
		return true
	case Ce:
		return true
	case Fcc:
		return true
	case Internal:
		return true
	case Miit:
		return true
	case Rohs:
		return true
	case Srrc:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for GearCertificationType.
const (
	Certification GearCertificationType = "certification"
	License       GearCertificationType = "license"
)

// Valid indicates whether the value is a known member of the GearCertificationType enum.
func (e GearCertificationType) Valid() bool {
	switch e {
	case Certification:
		return true
	case License:
		return true
	default:
		return false
	}
}

// Defines values for GearRole.
const (
	GearRoleAdmin       GearRole = "admin"
	GearRoleDevice      GearRole = "device"
	GearRolePeer        GearRole = "peer"
	GearRoleUnspecified GearRole = "unspecified"
)

// Valid indicates whether the value is a known member of the GearRole enum.
func (e GearRole) Valid() bool {
	switch e {
	case GearRoleAdmin:
		return true
	case GearRoleDevice:
		return true
	case GearRolePeer:
		return true
	case GearRoleUnspecified:
		return true
	default:
		return false
	}
}

// Defines values for GearStatus.
const (
	GearStatusActive      GearStatus = "active"
	GearStatusBlocked     GearStatus = "blocked"
	GearStatusUnspecified GearStatus = "unspecified"
)

// Valid indicates whether the value is a known member of the GearStatus enum.
func (e GearStatus) Valid() bool {
	switch e {
	case GearStatusActive:
		return true
	case GearStatusBlocked:
		return true
	case GearStatusUnspecified:
		return true
	default:
		return false
	}
}

// ApproveRequest defines model for ApproveRequest.
type ApproveRequest struct {
	Role GearRole `json:"role"`
}

// Channel defines model for Channel.
type Channel = string

// Configuration defines model for Configuration.
type Configuration struct {
	Certifications *[]GearCertification `json:"certifications,omitempty"`
	Firmware       *FirmwareConfig      `json:"firmware,omitempty"`
}

// Depot defines model for Depot.
type Depot struct {
	Beta     DepotRelease `json:"beta"`
	Info     DepotInfo    `json:"info"`
	Name     string       `json:"name"`
	Rollback DepotRelease `json:"rollback"`
	Stable   DepotRelease `json:"stable"`
	Testing  DepotRelease `json:"testing"`
}

// DepotFile defines model for DepotFile.
type DepotFile struct {
	Md5    string `json:"md5"`
	Path   string `json:"path"`
	Sha256 string `json:"sha256"`
}

// DepotInfo defines model for DepotInfo.
type DepotInfo struct {
	Files *[]DepotInfoFile `json:"files,omitempty"`
}

// DepotInfoFile defines model for DepotInfoFile.
type DepotInfoFile struct {
	Path string `json:"path"`
}

// DepotList defines model for DepotList.
type DepotList struct {
	Items []Depot `json:"items"`
}

// DepotRelease defines model for DepotRelease.
type DepotRelease struct {
	Channel        *string      `json:"channel,omitempty"`
	Files          *[]DepotFile `json:"files,omitempty"`
	FirmwareSemver string       `json:"firmware_semver"`
}

// DeviceInfo defines model for DeviceInfo.
type DeviceInfo struct {
	Hardware *HardwareInfo `json:"hardware,omitempty"`
	Name     *string       `json:"name,omitempty"`
	Sn       *string       `json:"sn,omitempty"`
}

// ErrorPayload defines model for ErrorPayload.
type ErrorPayload struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorPayload `json:"error"`
}

// FirmwareConfig defines model for FirmwareConfig.
type FirmwareConfig struct {
	Channel *GearFirmwareChannel `json:"channel,omitempty"`
}

// Gear defines model for Gear.
type Gear struct {
	ApprovedAt     *time.Time    `json:"approved_at,omitempty"`
	AutoRegistered *bool         `json:"auto_registered,omitempty"`
	Configuration  Configuration `json:"configuration"`
	CreatedAt      time.Time     `json:"created_at"`
	Device         DeviceInfo    `json:"device"`
	PublicKey      string        `json:"public_key"`
	Role           GearRole      `json:"role"`
	Status         GearStatus    `json:"status"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

// GearCertification defines model for GearCertification.
type GearCertification struct {
	Authority     GearCertificationAuthority `json:"authority"`
	AuthorityName *string                    `json:"authority_name,omitempty"`
	Id            string                     `json:"id"`
	Type          GearCertificationType      `json:"type"`
}

// GearCertificationAuthority defines model for GearCertificationAuthority.
type GearCertificationAuthority string

// GearCertificationType defines model for GearCertificationType.
type GearCertificationType string

// GearFirmwareChannel defines model for GearFirmwareChannel.
type GearFirmwareChannel = string

// GearIMEI defines model for GearIMEI.
type GearIMEI struct {
	Name   *string `json:"name,omitempty"`
	Serial string  `json:"serial"`
	Tac    string  `json:"tac"`
}

// GearLabel defines model for GearLabel.
type GearLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GearRole defines model for GearRole.
type GearRole string

// GearStatus defines model for GearStatus.
type GearStatus string

// HardwareInfo defines model for HardwareInfo.
type HardwareInfo struct {
	Depot            *string      `json:"depot,omitempty"`
	FirmwareSemver   *string      `json:"firmware_semver,omitempty"`
	HardwareRevision *string      `json:"hardware_revision,omitempty"`
	Imeis            *[]GearIMEI  `json:"imeis,omitempty"`
	Labels           *[]GearLabel `json:"labels,omitempty"`
	Manufacturer     *string      `json:"manufacturer,omitempty"`
	Model            *string      `json:"model,omitempty"`
}

// OTASummary defines model for OTASummary.
type OTASummary struct {
	Channel        string      `json:"channel"`
	Depot          string      `json:"depot"`
	Files          []DepotFile `json:"files"`
	FirmwareSemver string      `json:"firmware_semver"`
}

// PublicKeyResponse defines model for PublicKeyResponse.
type PublicKeyResponse struct {
	PublicKey string `json:"public_key"`
}

// RefreshResult defines model for RefreshResult.
type RefreshResult struct {
	Errors        *[]string `json:"errors,omitempty"`
	Gear          Gear      `json:"gear"`
	UpdatedFields *[]string `json:"updated_fields,omitempty"`
}

// Registration defines model for Registration.
type Registration struct {
	ApprovedAt     *time.Time `json:"approved_at,omitempty"`
	AutoRegistered *bool      `json:"auto_registered,omitempty"`
	CreatedAt      time.Time  `json:"created_at"`
	PublicKey      string     `json:"public_key"`
	Role           GearRole   `json:"role"`
	Status         GearStatus `json:"status"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

// RegistrationList defines model for RegistrationList.
type RegistrationList struct {
	Items []Registration `json:"items"`
}

// RegistrationRequest defines model for RegistrationRequest.
type RegistrationRequest struct {
	Device            DeviceInfo `json:"device"`
	PublicKey         string     `json:"public_key"`
	RegistrationToken *string    `json:"registration_token,omitempty"`
}

// RegistrationResult defines model for RegistrationResult.
type RegistrationResult struct {
	Gear         Gear         `json:"gear"`
	Registration Registration `json:"registration"`
}

// Runtime defines model for Runtime.
type Runtime struct {
	LastAddr   *string   `json:"last_addr,omitempty"`
	LastSeenAt time.Time `json:"last_seen_at"`
	Online     bool      `json:"online"`
}

// ServerInfo defines model for ServerInfo.
type ServerInfo struct {
	BuildCommit string `json:"build_commit"`
	PublicKey   string `json:"public_key"`
	ServerTime  int64  `json:"server_time"`
}

// RegisterGearJSONRequestBody defines body for RegisterGear for application/json ContentType.
type RegisterGearJSONRequestBody = RegistrationRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// RegisterGearWithBody request with any body
	RegisterGearWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RegisterGear(ctx context.Context, body RegisterGearJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetServerInfo request
	GetServerInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) RegisterGearWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterGearRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RegisterGear(ctx context.Context, body RegisterGearJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRegisterGearRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetServerInfo(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetServerInfoRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewRegisterGearRequest calls the generic RegisterGear builder with application/json body
func NewRegisterGearRequest(server string, body RegisterGearJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRegisterGearRequestWithBody(server, "application/json", bodyReader)
}

// NewRegisterGearRequestWithBody generates requests for RegisterGear with any type of body
func NewRegisterGearRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/register")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetServerInfoRequest generates requests for GetServerInfo
func NewGetServerInfoRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/server-info")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// RegisterGearWithBodyWithResponse request with any body
	RegisterGearWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterGearResponse, error)

	RegisterGearWithResponse(ctx context.Context, body RegisterGearJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterGearResponse, error)

	// GetServerInfoWithResponse request
	GetServerInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetServerInfoResponse, error)
}

type RegisterGearResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RegistrationResult
	JSON400      *ErrorResponse
	JSON409      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r RegisterGearResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RegisterGearResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetServerInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ServerInfo
	JSON400      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetServerInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetServerInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// RegisterGearWithBodyWithResponse request with arbitrary body returning *RegisterGearResponse
func (c *ClientWithResponses) RegisterGearWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RegisterGearResponse, error) {
	rsp, err := c.RegisterGearWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterGearResponse(rsp)
}

func (c *ClientWithResponses) RegisterGearWithResponse(ctx context.Context, body RegisterGearJSONRequestBody, reqEditors ...RequestEditorFn) (*RegisterGearResponse, error) {
	rsp, err := c.RegisterGear(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRegisterGearResponse(rsp)
}

// GetServerInfoWithResponse request returning *GetServerInfoResponse
func (c *ClientWithResponses) GetServerInfoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetServerInfoResponse, error) {
	rsp, err := c.GetServerInfo(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetServerInfoResponse(rsp)
}

// ParseRegisterGearResponse parses an HTTP response from a RegisterGearWithResponse call
func ParseRegisterGearResponse(rsp *http.Response) (*RegisterGearResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RegisterGearResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RegistrationResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetServerInfoResponse parses an HTTP response from a GetServerInfoWithResponse call
func ParseGetServerInfoResponse(rsp *http.Response) (*GetServerInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetServerInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ServerInfo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register a gear
	// (POST /register)
	RegisterGear(c *fiber.Ctx) error
	// Get server information
	// (GET /server-info)
	GetServerInfo(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// RegisterGear operation middleware
func (siw *ServerInterfaceWrapper) RegisterGear(c *fiber.Ctx) error {

	return siw.Handler.RegisterGear(c)
}

// GetServerInfo operation middleware
func (siw *ServerInterfaceWrapper) GetServerInfo(c *fiber.Ctx) error {

	return siw.Handler.GetServerInfo(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/register", wrapper.RegisterGear)

	router.Get(options.BaseURL+"/server-info", wrapper.GetServerInfo)

}

type RegisterGearRequestObject struct {
	Body *RegisterGearJSONRequestBody
}

type RegisterGearResponseObject interface {
	VisitRegisterGearResponse(ctx *fiber.Ctx) error
}

type RegisterGear200JSONResponse RegistrationResult

func (response RegisterGear200JSONResponse) VisitRegisterGearResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type RegisterGear400JSONResponse ErrorResponse

func (response RegisterGear400JSONResponse) VisitRegisterGearResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type RegisterGear409JSONResponse ErrorResponse

func (response RegisterGear409JSONResponse) VisitRegisterGearResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type GetServerInfoRequestObject struct {
}

type GetServerInfoResponseObject interface {
	VisitGetServerInfoResponse(ctx *fiber.Ctx) error
}

type GetServerInfo200JSONResponse ServerInfo

func (response GetServerInfo200JSONResponse) VisitGetServerInfoResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetServerInfo400JSONResponse ErrorResponse

func (response GetServerInfo400JSONResponse) VisitGetServerInfoResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Register a gear
	// (POST /register)
	RegisterGear(ctx context.Context, request RegisterGearRequestObject) (RegisterGearResponseObject, error)
	// Get server information
	// (GET /server-info)
	GetServerInfo(ctx context.Context, request GetServerInfoRequestObject) (GetServerInfoResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// RegisterGear operation middleware
func (sh *strictHandler) RegisterGear(ctx *fiber.Ctx) error {
	var request RegisterGearRequestObject

	var body RegisterGearJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterGear(ctx.UserContext(), request.(RegisterGearRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterGear")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(RegisterGearResponseObject); ok {
		if err := validResponse.VisitRegisterGearResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetServerInfo operation middleware
func (sh *strictHandler) GetServerInfo(ctx *fiber.Ctx) error {
	var request GetServerInfoRequestObject

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetServerInfo(ctx.UserContext(), request.(GetServerInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetServerInfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(GetServerInfoResponseObject); ok {
		if err := validResponse.VisitGetServerInfoResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
