// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apitypes

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ApplyAction.
const (
	ApplyActionApplied   ApplyAction = "applied"
	ApplyActionCreated   ApplyAction = "created"
	ApplyActionUnchanged ApplyAction = "unchanged"
	ApplyActionUpdated   ApplyAction = "updated"
)

// Valid indicates whether the value is a known member of the ApplyAction enum.
func (e ApplyAction) Valid() bool {
	switch e {
	case ApplyActionApplied:
		return true
	case ApplyActionCreated:
		return true
	case ApplyActionUnchanged:
		return true
	case ApplyActionUpdated:
		return true
	default:
		return false
	}
}

// Defines values for CredentialMethod.
const (
	CredentialMethodApiKey     CredentialMethod = "api_key"
	CredentialMethodAppIdToken CredentialMethod = "app_id_token"
	CredentialMethodToken      CredentialMethod = "token"
)

// Valid indicates whether the value is a known member of the CredentialMethod enum.
func (e CredentialMethod) Valid() bool {
	switch e {
	case CredentialMethodApiKey:
		return true
	case CredentialMethodAppIdToken:
		return true
	case CredentialMethodToken:
		return true
	default:
		return false
	}
}

// Defines values for CredentialResourceKind.
const (
	CredentialResourceKindCredential CredentialResourceKind = "Credential"
)

// Valid indicates whether the value is a known member of the CredentialResourceKind enum.
func (e CredentialResourceKind) Valid() bool {
	switch e {
	case CredentialResourceKindCredential:
		return true
	default:
		return false
	}
}

// Defines values for FlowcraftWorkflowKind.
const (
	FlowcraftWorkflowKindFlowcraftWorkflow FlowcraftWorkflowKind = "FlowcraftWorkflow"
)

// Valid indicates whether the value is a known member of the FlowcraftWorkflowKind enum.
func (e FlowcraftWorkflowKind) Valid() bool {
	switch e {
	case FlowcraftWorkflowKindFlowcraftWorkflow:
		return true
	default:
		return false
	}
}

// Defines values for GearCertificationAuthority.
const (
	GearCertificationAuthorityCcc      GearCertificationAuthority = "ccc"
	GearCertificationAuthorityCe       GearCertificationAuthority = "ce"
	GearCertificationAuthorityFcc      GearCertificationAuthority = "fcc"
	GearCertificationAuthorityInternal GearCertificationAuthority = "internal"
	GearCertificationAuthorityMiit     GearCertificationAuthority = "miit"
	GearCertificationAuthorityRohs     GearCertificationAuthority = "rohs"
	GearCertificationAuthoritySrrc     GearCertificationAuthority = "srrc"
	GearCertificationAuthorityUnknown  GearCertificationAuthority = "unknown"
)

// Valid indicates whether the value is a known member of the GearCertificationAuthority enum.
func (e GearCertificationAuthority) Valid() bool {
	switch e {
	case GearCertificationAuthorityCcc:
		return true
	case GearCertificationAuthorityCe:
		return true
	case GearCertificationAuthorityFcc:
		return true
	case GearCertificationAuthorityInternal:
		return true
	case GearCertificationAuthorityMiit:
		return true
	case GearCertificationAuthorityRohs:
		return true
	case GearCertificationAuthoritySrrc:
		return true
	case GearCertificationAuthorityUnknown:
		return true
	default:
		return false
	}
}

// Defines values for GearCertificationType.
const (
	GearCertificationTypeCertification GearCertificationType = "certification"
	GearCertificationTypeLicense       GearCertificationType = "license"
)

// Valid indicates whether the value is a known member of the GearCertificationType enum.
func (e GearCertificationType) Valid() bool {
	switch e {
	case GearCertificationTypeCertification:
		return true
	case GearCertificationTypeLicense:
		return true
	default:
		return false
	}
}

// Defines values for GearRole.
const (
	GearRoleAdmin       GearRole = "admin"
	GearRoleGear        GearRole = "gear"
	GearRoleServer      GearRole = "server"
	GearRoleUnspecified GearRole = "unspecified"
)

// Valid indicates whether the value is a known member of the GearRole enum.
func (e GearRole) Valid() bool {
	switch e {
	case GearRoleAdmin:
		return true
	case GearRoleGear:
		return true
	case GearRoleServer:
		return true
	case GearRoleUnspecified:
		return true
	default:
		return false
	}
}

// Defines values for GearStatus.
const (
	GearStatusActive      GearStatus = "active"
	GearStatusBlocked     GearStatus = "blocked"
	GearStatusUnspecified GearStatus = "unspecified"
)

// Valid indicates whether the value is a known member of the GearStatus enum.
func (e GearStatus) Valid() bool {
	switch e {
	case GearStatusActive:
		return true
	case GearStatusBlocked:
		return true
	case GearStatusUnspecified:
		return true
	default:
		return false
	}
}

// Defines values for MiniMaxTenantResourceKind.
const (
	MiniMaxTenantResourceKindMiniMaxTenant MiniMaxTenantResourceKind = "MiniMaxTenant"
)

// Valid indicates whether the value is a known member of the MiniMaxTenantResourceKind enum.
func (e MiniMaxTenantResourceKind) Valid() bool {
	switch e {
	case MiniMaxTenantResourceKindMiniMaxTenant:
		return true
	default:
		return false
	}
}

// Defines values for ModelKind.
const (
	ModelKindAsr ModelKind = "asr"
	ModelKindLlm ModelKind = "llm"
	ModelKindTts ModelKind = "tts"
)

// Valid indicates whether the value is a known member of the ModelKind enum.
func (e ModelKind) Valid() bool {
	switch e {
	case ModelKindAsr:
		return true
	case ModelKindLlm:
		return true
	case ModelKindTts:
		return true
	default:
		return false
	}
}

// Defines values for ModelResourceKind.
const (
	ModelResourceKindModel ModelResourceKind = "Model"
)

// Valid indicates whether the value is a known member of the ModelResourceKind enum.
func (e ModelResourceKind) Valid() bool {
	switch e {
	case ModelResourceKindModel:
		return true
	default:
		return false
	}
}

// Defines values for ModelSource.
const (
	ModelSourceManual ModelSource = "manual"
	ModelSourceSync   ModelSource = "sync"
)

// Valid indicates whether the value is a known member of the ModelSource enum.
func (e ModelSource) Valid() bool {
	switch e {
	case ModelSourceManual:
		return true
	case ModelSourceSync:
		return true
	default:
		return false
	}
}

// Defines values for PeerConfigResourceKind.
const (
	PeerConfigResourceKindPeerConfig PeerConfigResourceKind = "PeerConfig"
)

// Valid indicates whether the value is a known member of the PeerConfigResourceKind enum.
func (e PeerConfigResourceKind) Valid() bool {
	switch e {
	case PeerConfigResourceKindPeerConfig:
		return true
	default:
		return false
	}
}

// Defines values for ResourceAPIVersion.
const (
	ResourceAPIVersionGizclawAdminv1alpha1 ResourceAPIVersion = "gizclaw.admin/v1alpha1"
)

// Valid indicates whether the value is a known member of the ResourceAPIVersion enum.
func (e ResourceAPIVersion) Valid() bool {
	switch e {
	case ResourceAPIVersionGizclawAdminv1alpha1:
		return true
	default:
		return false
	}
}

// Defines values for ResourceKind.
const (
	ResourceKindCredential    ResourceKind = "Credential"
	ResourceKindMiniMaxTenant ResourceKind = "MiniMaxTenant"
	ResourceKindModel         ResourceKind = "Model"
	ResourceKindPeerConfig    ResourceKind = "PeerConfig"
	ResourceKindResourceList  ResourceKind = "ResourceList"
	ResourceKindVoice         ResourceKind = "Voice"
	ResourceKindVolcTenant    ResourceKind = "VolcTenant"
	ResourceKindWorkflow      ResourceKind = "Workflow"
	ResourceKindWorkspace     ResourceKind = "Workspace"
)

// Valid indicates whether the value is a known member of the ResourceKind enum.
func (e ResourceKind) Valid() bool {
	switch e {
	case ResourceKindCredential:
		return true
	case ResourceKindMiniMaxTenant:
		return true
	case ResourceKindModel:
		return true
	case ResourceKindPeerConfig:
		return true
	case ResourceKindResourceList:
		return true
	case ResourceKindVoice:
		return true
	case ResourceKindVolcTenant:
		return true
	case ResourceKindWorkflow:
		return true
	case ResourceKindWorkspace:
		return true
	default:
		return false
	}
}

// Defines values for ResourceListResourceKind.
const (
	ResourceListResourceKindResourceList ResourceListResourceKind = "ResourceList"
)

// Valid indicates whether the value is a known member of the ResourceListResourceKind enum.
func (e ResourceListResourceKind) Valid() bool {
	switch e {
	case ResourceListResourceKindResourceList:
		return true
	default:
		return false
	}
}

// Defines values for VoiceResourceKind.
const (
	VoiceResourceKindVoice VoiceResourceKind = "Voice"
)

// Valid indicates whether the value is a known member of the VoiceResourceKind enum.
func (e VoiceResourceKind) Valid() bool {
	switch e {
	case VoiceResourceKindVoice:
		return true
	default:
		return false
	}
}

// Defines values for VoiceSource.
const (
	VoiceSourceManual VoiceSource = "manual"
	VoiceSourceSync   VoiceSource = "sync"
)

// Valid indicates whether the value is a known member of the VoiceSource enum.
func (e VoiceSource) Valid() bool {
	switch e {
	case VoiceSourceManual:
		return true
	case VoiceSourceSync:
		return true
	default:
		return false
	}
}

// Defines values for VolcTenantResourceKind.
const (
	VolcTenantResourceKindVolcTenant VolcTenantResourceKind = "VolcTenant"
)

// Valid indicates whether the value is a known member of the VolcTenantResourceKind enum.
func (e VolcTenantResourceKind) Valid() bool {
	switch e {
	case VolcTenantResourceKindVolcTenant:
		return true
	default:
		return false
	}
}

// Defines values for WorkflowAPIVersion.
const (
	WorkflowAPIVersionGizclawFlowcraftv1alpha1 WorkflowAPIVersion = "gizclaw.flowcraft/v1alpha1"
)

// Valid indicates whether the value is a known member of the WorkflowAPIVersion enum.
func (e WorkflowAPIVersion) Valid() bool {
	switch e {
	case WorkflowAPIVersionGizclawFlowcraftv1alpha1:
		return true
	default:
		return false
	}
}

// Defines values for WorkflowResourceKind.
const (
	WorkflowResourceKindWorkflow WorkflowResourceKind = "Workflow"
)

// Valid indicates whether the value is a known member of the WorkflowResourceKind enum.
func (e WorkflowResourceKind) Valid() bool {
	switch e {
	case WorkflowResourceKindWorkflow:
		return true
	default:
		return false
	}
}

// Defines values for WorkspaceResourceKind.
const (
	WorkspaceResourceKindWorkspace WorkspaceResourceKind = "Workspace"
)

// Valid indicates whether the value is a known member of the WorkspaceResourceKind enum.
func (e WorkspaceResourceKind) Valid() bool {
	switch e {
	case WorkspaceResourceKindWorkspace:
		return true
	default:
		return false
	}
}

// ApplyAction Result of applying the resource.
type ApplyAction string

// ApplyResource defines model for ApplyResource.
type ApplyResource = Resource

// ApplyResult defines model for ApplyResult.
type ApplyResult struct {
	// Action Result of applying the resource.
	Action ApplyAction `json:"action"`

	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion `json:"apiVersion"`

	// Items Nested apply results for ResourceList resources.
	Items *[]ApplyResult `json:"items,omitempty"`

	// Kind Declarative GizClaw resource kind.
	Kind    ResourceKind `json:"kind"`
	Message *string      `json:"message,omitempty"`
	Name    string       `json:"name"`
}

// Channel defines model for Channel.
type Channel = string

// Configuration defines model for Configuration.
type Configuration struct {
	Certifications *[]GearCertification `json:"certifications,omitempty"`
	Firmware       *FirmwareConfig      `json:"firmware,omitempty"`
}

// Credential defines model for Credential.
type Credential struct {
	Body        CredentialBody `json:"body"`
	CreatedAt   time.Time      `json:"created_at"`
	Description *string        `json:"description,omitempty"`

	// Method Credential authentication method
	Method CredentialMethod `json:"method"`

	// Name Credential name
	Name CredentialName `json:"name"`

	// Provider Credential provider name
	Provider  CredentialProvider `json:"provider"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// CredentialBody defines model for CredentialBody.
type CredentialBody map[string]interface{}

// CredentialMethod Credential authentication method
type CredentialMethod string

// CredentialName Credential name
type CredentialName = string

// CredentialProvider Credential provider name
type CredentialProvider = string

// CredentialResource defines model for CredentialResource.
type CredentialResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion     `json:"apiVersion"`
	Kind       CredentialResourceKind `json:"kind"`
	Metadata   ResourceMetadata       `json:"metadata"`
	Spec       CredentialSpec         `json:"spec"`
}

// CredentialResourceKind defines model for CredentialResource.Kind.
type CredentialResourceKind string

// CredentialSpec defines model for CredentialSpec.
type CredentialSpec struct {
	Body        CredentialBody `json:"body"`
	Description *string        `json:"description,omitempty"`

	// Method Credential authentication method
	Method CredentialMethod `json:"method"`

	// Provider Credential provider name
	Provider CredentialProvider `json:"provider"`
}

// Depot defines model for Depot.
type Depot struct {
	Beta     DepotRelease `json:"beta"`
	Info     DepotInfo    `json:"info"`
	Name     string       `json:"name"`
	Rollback DepotRelease `json:"rollback"`
	Stable   DepotRelease `json:"stable"`
	Testing  DepotRelease `json:"testing"`
}

// DepotFile defines model for DepotFile.
type DepotFile struct {
	Md5    string `json:"md5"`
	Path   string `json:"path"`
	Sha256 string `json:"sha256"`
}

// DepotInfo defines model for DepotInfo.
type DepotInfo struct {
	Files *[]DepotInfoFile `json:"files,omitempty"`
}

// DepotInfoFile defines model for DepotInfoFile.
type DepotInfoFile struct {
	Path string `json:"path"`
}

// DepotRelease defines model for DepotRelease.
type DepotRelease struct {
	Channel        *string      `json:"channel,omitempty"`
	Files          *[]DepotFile `json:"files,omitempty"`
	FirmwareSemver string       `json:"firmware_semver"`
}

// DeviceInfo defines model for DeviceInfo.
type DeviceInfo struct {
	Hardware *HardwareInfo `json:"hardware,omitempty"`
	Name     *string       `json:"name,omitempty"`
	Sn       *string       `json:"sn,omitempty"`
}

// ErrorPayload defines model for ErrorPayload.
type ErrorPayload struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error ErrorPayload `json:"error"`
}

// Event defines model for Event.
type Event struct {
	Data *json.RawMessage `json:"data,omitempty"`
	Name string           `json:"name"`
	V    int              `json:"v"`
}

// FirmwareConfig defines model for FirmwareConfig.
type FirmwareConfig struct {
	Channel *GearFirmwareChannel `json:"channel,omitempty"`
}

// FlowcraftWorkflow defines model for FlowcraftWorkflow.
type FlowcraftWorkflow struct {
	ApiVersion WorkflowAPIVersion    `json:"apiVersion"`
	Kind       FlowcraftWorkflowKind `json:"kind"`
	Metadata   WorkflowMetadata      `json:"metadata"`
	Spec       FlowcraftWorkflowSpec `json:"spec"`
}

// FlowcraftWorkflowKind defines model for FlowcraftWorkflow.Kind.
type FlowcraftWorkflowKind string

// FlowcraftWorkflowSpec defines model for FlowcraftWorkflowSpec.
type FlowcraftWorkflowSpec map[string]interface{}

// Gear defines model for Gear.
type Gear struct {
	ApprovedAt     *time.Time    `json:"approved_at,omitempty"`
	AutoRegistered *bool         `json:"auto_registered,omitempty"`
	Configuration  Configuration `json:"configuration"`
	CreatedAt      time.Time     `json:"created_at"`
	Device         DeviceInfo    `json:"device"`
	PublicKey      string        `json:"public_key"`
	Role           GearRole      `json:"role"`
	Status         GearStatus    `json:"status"`
	UpdatedAt      time.Time     `json:"updated_at"`
}

// GearCertification defines model for GearCertification.
type GearCertification struct {
	Authority     GearCertificationAuthority `json:"authority"`
	AuthorityName *string                    `json:"authority_name,omitempty"`
	Id            string                     `json:"id"`
	Type          GearCertificationType      `json:"type"`
}

// GearCertificationAuthority defines model for GearCertificationAuthority.
type GearCertificationAuthority string

// GearCertificationType defines model for GearCertificationType.
type GearCertificationType string

// GearFirmwareChannel defines model for GearFirmwareChannel.
type GearFirmwareChannel = string

// GearIMEI defines model for GearIMEI.
type GearIMEI struct {
	Name   *string `json:"name,omitempty"`
	Serial string  `json:"serial"`
	Tac    string  `json:"tac"`
}

// GearLabel defines model for GearLabel.
type GearLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GearRole defines model for GearRole.
type GearRole string

// GearStatus defines model for GearStatus.
type GearStatus string

// HardwareInfo defines model for HardwareInfo.
type HardwareInfo struct {
	Depot            *string      `json:"depot,omitempty"`
	FirmwareSemver   *string      `json:"firmware_semver,omitempty"`
	HardwareRevision *string      `json:"hardware_revision,omitempty"`
	Imeis            *[]GearIMEI  `json:"imeis,omitempty"`
	Labels           *[]GearLabel `json:"labels,omitempty"`
	Manufacturer     *string      `json:"manufacturer,omitempty"`
	Model            *string      `json:"model,omitempty"`
}

// MiniMaxAppID MiniMax app identifier
type MiniMaxAppID = string

// MiniMaxGroupID MiniMax group identifier
type MiniMaxGroupID = string

// MiniMaxTenant defines model for MiniMaxTenant.
type MiniMaxTenant struct {
	// AppId MiniMax app identifier
	AppId     MiniMaxAppID `json:"app_id"`
	BaseUrl   *string      `json:"base_url,omitempty"`
	CreatedAt time.Time    `json:"created_at"`

	// CredentialName Credential name
	CredentialName CredentialName `json:"credential_name"`
	Description    *string        `json:"description,omitempty"`

	// GroupId MiniMax group identifier
	GroupId      MiniMaxGroupID `json:"group_id"`
	LastSyncedAt *time.Time     `json:"last_synced_at,omitempty"`

	// Name MiniMax tenant name
	Name      MiniMaxTenantName `json:"name"`
	UpdatedAt time.Time         `json:"updated_at"`
}

// MiniMaxTenantName MiniMax tenant name
type MiniMaxTenantName = string

// MiniMaxTenantResource defines model for MiniMaxTenantResource.
type MiniMaxTenantResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion        `json:"apiVersion"`
	Kind       MiniMaxTenantResourceKind `json:"kind"`
	Metadata   ResourceMetadata          `json:"metadata"`
	Spec       MiniMaxTenantSpec         `json:"spec"`
}

// MiniMaxTenantResourceKind defines model for MiniMaxTenantResource.Kind.
type MiniMaxTenantResourceKind string

// MiniMaxTenantSpec defines model for MiniMaxTenantSpec.
type MiniMaxTenantSpec struct {
	// AppId MiniMax app identifier
	AppId   MiniMaxAppID `json:"app_id"`
	BaseUrl *string      `json:"base_url,omitempty"`

	// CredentialName Credential name
	CredentialName CredentialName `json:"credential_name"`
	Description    *string        `json:"description,omitempty"`

	// GroupId MiniMax group identifier
	GroupId MiniMaxGroupID `json:"group_id"`
}

// Model defines model for Model.
type Model struct {
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`

	// Id Global model identifier
	Id ModelID `json:"id"`

	// Kind Model capability kind
	Kind     ModelKind     `json:"kind"`
	Name     *string       `json:"name,omitempty"`
	Provider ModelProvider `json:"provider"`

	// ProviderData Provider-specific data keyed by provider kind.
	ProviderData *map[string]interface{} `json:"provider_data,omitempty"`

	// Source How the model entered the global catalog
	Source    ModelSource `json:"source"`
	SyncedAt  *time.Time  `json:"synced_at,omitempty"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// ModelID Global model identifier
type ModelID = string

// ModelKind Model capability kind
type ModelKind string

// ModelProvider defines model for ModelProvider.
type ModelProvider struct {
	// Kind Model provider kind
	Kind ModelProviderKind `json:"kind"`

	// Name Model provider instance name
	Name ModelProviderName `json:"name"`
}

// ModelProviderKind Model provider kind
type ModelProviderKind = string

// ModelProviderName Model provider instance name
type ModelProviderName = string

// ModelResource defines model for ModelResource.
type ModelResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion `json:"apiVersion"`
	Kind       ModelResourceKind  `json:"kind"`
	Metadata   ResourceMetadata   `json:"metadata"`
	Spec       ModelSpec          `json:"spec"`
}

// ModelResourceKind defines model for ModelResource.Kind.
type ModelResourceKind string

// ModelSource How the model entered the global catalog
type ModelSource string

// ModelSpec defines model for ModelSpec.
type ModelSpec struct {
	Description *string `json:"description,omitempty"`

	// Kind Model capability kind
	Kind     ModelKind     `json:"kind"`
	Name     *string       `json:"name,omitempty"`
	Provider ModelProvider `json:"provider"`

	// ProviderData Provider-specific data keyed by provider kind.
	ProviderData *map[string]interface{} `json:"provider_data,omitempty"`

	// Source How the model entered the global catalog
	Source ModelSource `json:"source"`
}

// OTASummary defines model for OTASummary.
type OTASummary struct {
	Channel        string      `json:"channel"`
	Depot          string      `json:"depot"`
	Files          []DepotFile `json:"files"`
	FirmwareSemver string      `json:"firmware_semver"`
}

// PeerConfigResource defines model for PeerConfigResource.
type PeerConfigResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion     `json:"apiVersion"`
	Kind       PeerConfigResourceKind `json:"kind"`
	Metadata   ResourceMetadata       `json:"metadata"`
	Spec       Configuration          `json:"spec"`
}

// PeerConfigResourceKind defines model for PeerConfigResource.Kind.
type PeerConfigResourceKind string

// RefreshIdentifiers defines model for RefreshIdentifiers.
type RefreshIdentifiers struct {
	Imeis  *[]GearIMEI  `json:"imeis,omitempty"`
	Labels *[]GearLabel `json:"labels,omitempty"`
	Sn     *string      `json:"sn,omitempty"`
}

// RefreshInfo defines model for RefreshInfo.
type RefreshInfo struct {
	HardwareRevision *string `json:"hardware_revision,omitempty"`
	Manufacturer     *string `json:"manufacturer,omitempty"`
	Model            *string `json:"model,omitempty"`
	Name             *string `json:"name,omitempty"`
}

// RefreshVersion defines model for RefreshVersion.
type RefreshVersion struct {
	Depot          *string `json:"depot,omitempty"`
	FirmwareSemver *string `json:"firmware_semver,omitempty"`
}

// Registration defines model for Registration.
type Registration struct {
	ApprovedAt     *time.Time  `json:"approved_at,omitempty"`
	AutoRegistered *bool       `json:"auto_registered,omitempty"`
	CreatedAt      time.Time   `json:"created_at"`
	Device         *DeviceInfo `json:"device,omitempty"`
	PublicKey      string      `json:"public_key"`
	Role           GearRole    `json:"role"`
	Status         GearStatus  `json:"status"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

// Resource defines model for Resource.
type Resource struct {
	union json.RawMessage
}

// ResourceAPIVersion API version for declarative GizClaw resources.
type ResourceAPIVersion string

// ResourceKind Declarative GizClaw resource kind.
type ResourceKind string

// ResourceList defines model for ResourceList.
type ResourceList = ResourceListResource

// ResourceListResource defines model for ResourceListResource.
type ResourceListResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion       `json:"apiVersion"`
	Kind       ResourceListResourceKind `json:"kind"`
	Metadata   ResourceMetadata         `json:"metadata"`
	Spec       ResourceListSpec         `json:"spec"`
}

// ResourceListResourceKind defines model for ResourceListResource.Kind.
type ResourceListResourceKind string

// ResourceListSpec defines model for ResourceListSpec.
type ResourceListSpec struct {
	Items []Resource `json:"items"`
}

// ResourceMetadata defines model for ResourceMetadata.
type ResourceMetadata struct {
	Annotations *map[string]string `json:"annotations,omitempty"`
	Labels      *map[string]string `json:"labels,omitempty"`

	// Name Resource name. For PeerConfig this is the peer public key.
	Name string `json:"name"`
}

// Runtime defines model for Runtime.
type Runtime struct {
	LastAddr   *string   `json:"last_addr,omitempty"`
	LastSeenAt time.Time `json:"last_seen_at"`
	Online     bool      `json:"online"`
	RxBytes    *uint64   `json:"rx_bytes,omitempty"`
	TxBytes    *uint64   `json:"tx_bytes,omitempty"`
}

// ServerInfo defines model for ServerInfo.
type ServerInfo struct {
	BuildCommit string `json:"build_commit"`
	PublicKey   string `json:"public_key"`
	ServerTime  int64  `json:"server_time"`
}

// Voice defines model for Voice.
type Voice struct {
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`

	// Id Global voice identifier
	Id       VoiceID       `json:"id"`
	Name     *string       `json:"name,omitempty"`
	Provider VoiceProvider `json:"provider"`

	// ProviderData Provider-specific debug data keyed by provider kind.
	ProviderData *map[string]interface{} `json:"provider_data,omitempty"`

	// Source How the voice entered the global catalog
	Source    VoiceSource `json:"source"`
	SyncedAt  *time.Time  `json:"synced_at,omitempty"`
	UpdatedAt time.Time   `json:"updated_at"`
}

// VoiceID Global voice identifier
type VoiceID = string

// VoiceProvider defines model for VoiceProvider.
type VoiceProvider struct {
	// Kind Voice provider kind
	Kind VoiceProviderKind `json:"kind"`

	// Name Voice provider instance name
	Name VoiceProviderName `json:"name"`
}

// VoiceProviderKind Voice provider kind
type VoiceProviderKind = string

// VoiceProviderName Voice provider instance name
type VoiceProviderName = string

// VoiceResource defines model for VoiceResource.
type VoiceResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion `json:"apiVersion"`
	Kind       VoiceResourceKind  `json:"kind"`
	Metadata   ResourceMetadata   `json:"metadata"`
	Spec       VoiceSpec          `json:"spec"`
}

// VoiceResourceKind defines model for VoiceResource.Kind.
type VoiceResourceKind string

// VoiceSource How the voice entered the global catalog
type VoiceSource string

// VoiceSpec defines model for VoiceSpec.
type VoiceSpec struct {
	Description *string       `json:"description,omitempty"`
	Name        *string       `json:"name,omitempty"`
	Provider    VoiceProvider `json:"provider"`

	// ProviderData Provider-specific debug data keyed by provider kind.
	ProviderData *map[string]interface{} `json:"provider_data,omitempty"`

	// Source How the voice entered the global catalog
	Source VoiceSource `json:"source"`
}

// VolcAppID Volcengine speech application identifier
type VolcAppID = string

// VolcResourceID Volcengine speech resource identifier.
type VolcResourceID = string

// VolcTenant defines model for VolcTenant.
type VolcTenant struct {
	// AppId Volcengine speech application identifier
	AppId     VolcAppID `json:"app_id"`
	CreatedAt time.Time `json:"created_at"`

	// CredentialName Credential name
	CredentialName CredentialName `json:"credential_name"`
	Description    *string        `json:"description,omitempty"`
	Endpoint       *string        `json:"endpoint,omitempty"`
	LastSyncedAt   *time.Time     `json:"last_synced_at,omitempty"`

	// Name Volcengine tenant name.
	Name        VolcTenantName    `json:"name"`
	Region      *string           `json:"region,omitempty"`
	ResourceIds *[]VolcResourceID `json:"resource_ids,omitempty"`
	UpdatedAt   time.Time         `json:"updated_at"`
}

// VolcTenantName Volcengine tenant name.
type VolcTenantName = string

// VolcTenantResource defines model for VolcTenantResource.
type VolcTenantResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion     `json:"apiVersion"`
	Kind       VolcTenantResourceKind `json:"kind"`
	Metadata   ResourceMetadata       `json:"metadata"`
	Spec       VolcTenantSpec         `json:"spec"`
}

// VolcTenantResourceKind defines model for VolcTenantResource.Kind.
type VolcTenantResourceKind string

// VolcTenantSpec defines model for VolcTenantSpec.
type VolcTenantSpec struct {
	// AppId Volcengine speech application identifier
	AppId VolcAppID `json:"app_id"`

	// CredentialName Credential name
	CredentialName CredentialName    `json:"credential_name"`
	Description    *string           `json:"description,omitempty"`
	Endpoint       *string           `json:"endpoint,omitempty"`
	Region         *string           `json:"region,omitempty"`
	ResourceIds    *[]VolcResourceID `json:"resource_ids,omitempty"`
}

// WorkflowAPIVersion defines model for WorkflowAPIVersion.
type WorkflowAPIVersion string

// WorkflowDocument defines model for WorkflowDocument.
type WorkflowDocument = FlowcraftWorkflow

// WorkflowMetadata defines model for WorkflowMetadata.
type WorkflowMetadata struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// WorkflowName Workflow name
type WorkflowName = string

// WorkflowResource defines model for WorkflowResource.
type WorkflowResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion   `json:"apiVersion"`
	Kind       WorkflowResourceKind `json:"kind"`
	Metadata   ResourceMetadata     `json:"metadata"`
	Spec       WorkflowDocument     `json:"spec"`
}

// WorkflowResourceKind defines model for WorkflowResource.Kind.
type WorkflowResourceKind string

// Workspace defines model for Workspace.
type Workspace struct {
	CreatedAt time.Time `json:"created_at"`

	// Name Workspace name
	Name       WorkspaceName           `json:"name"`
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
	UpdatedAt  time.Time               `json:"updated_at"`

	// WorkflowName Workflow name
	WorkflowName WorkflowName `json:"workflow_name"`
}

// WorkspaceName Workspace name
type WorkspaceName = string

// WorkspaceResource defines model for WorkspaceResource.
type WorkspaceResource struct {
	// ApiVersion API version for declarative GizClaw resources.
	ApiVersion ResourceAPIVersion    `json:"apiVersion"`
	Kind       WorkspaceResourceKind `json:"kind"`
	Metadata   ResourceMetadata      `json:"metadata"`
	Spec       WorkspaceSpec         `json:"spec"`
}

// WorkspaceResourceKind defines model for WorkspaceResource.Kind.
type WorkspaceResourceKind string

// WorkspaceSpec defines model for WorkspaceSpec.
type WorkspaceSpec struct {
	Parameters *map[string]interface{} `json:"parameters,omitempty"`

	// WorkflowName Workflow name
	WorkflowName WorkflowName `json:"workflow_name"`
}

// AsCredentialResource returns the union data inside the Resource as a CredentialResource
func (t Resource) AsCredentialResource() (CredentialResource, error) {
	var body CredentialResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCredentialResource overwrites any union data inside the Resource as the provided CredentialResource
func (t *Resource) FromCredentialResource(v CredentialResource) error {
	v.Kind = "CredentialResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCredentialResource performs a merge with any union data inside the Resource, using the provided CredentialResource
func (t *Resource) MergeCredentialResource(v CredentialResource) error {
	v.Kind = "CredentialResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsModelResource returns the union data inside the Resource as a ModelResource
func (t Resource) AsModelResource() (ModelResource, error) {
	var body ModelResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromModelResource overwrites any union data inside the Resource as the provided ModelResource
func (t *Resource) FromModelResource(v ModelResource) error {
	v.Kind = "ModelResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeModelResource performs a merge with any union data inside the Resource, using the provided ModelResource
func (t *Resource) MergeModelResource(v ModelResource) error {
	v.Kind = "ModelResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMiniMaxTenantResource returns the union data inside the Resource as a MiniMaxTenantResource
func (t Resource) AsMiniMaxTenantResource() (MiniMaxTenantResource, error) {
	var body MiniMaxTenantResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMiniMaxTenantResource overwrites any union data inside the Resource as the provided MiniMaxTenantResource
func (t *Resource) FromMiniMaxTenantResource(v MiniMaxTenantResource) error {
	v.Kind = "MiniMaxTenantResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMiniMaxTenantResource performs a merge with any union data inside the Resource, using the provided MiniMaxTenantResource
func (t *Resource) MergeMiniMaxTenantResource(v MiniMaxTenantResource) error {
	v.Kind = "MiniMaxTenantResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVolcTenantResource returns the union data inside the Resource as a VolcTenantResource
func (t Resource) AsVolcTenantResource() (VolcTenantResource, error) {
	var body VolcTenantResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVolcTenantResource overwrites any union data inside the Resource as the provided VolcTenantResource
func (t *Resource) FromVolcTenantResource(v VolcTenantResource) error {
	v.Kind = "VolcTenantResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVolcTenantResource performs a merge with any union data inside the Resource, using the provided VolcTenantResource
func (t *Resource) MergeVolcTenantResource(v VolcTenantResource) error {
	v.Kind = "VolcTenantResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVoiceResource returns the union data inside the Resource as a VoiceResource
func (t Resource) AsVoiceResource() (VoiceResource, error) {
	var body VoiceResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVoiceResource overwrites any union data inside the Resource as the provided VoiceResource
func (t *Resource) FromVoiceResource(v VoiceResource) error {
	v.Kind = "VoiceResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVoiceResource performs a merge with any union data inside the Resource, using the provided VoiceResource
func (t *Resource) MergeVoiceResource(v VoiceResource) error {
	v.Kind = "VoiceResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWorkflowResource returns the union data inside the Resource as a WorkflowResource
func (t Resource) AsWorkflowResource() (WorkflowResource, error) {
	var body WorkflowResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWorkflowResource overwrites any union data inside the Resource as the provided WorkflowResource
func (t *Resource) FromWorkflowResource(v WorkflowResource) error {
	v.Kind = "WorkflowResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWorkflowResource performs a merge with any union data inside the Resource, using the provided WorkflowResource
func (t *Resource) MergeWorkflowResource(v WorkflowResource) error {
	v.Kind = "WorkflowResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWorkspaceResource returns the union data inside the Resource as a WorkspaceResource
func (t Resource) AsWorkspaceResource() (WorkspaceResource, error) {
	var body WorkspaceResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWorkspaceResource overwrites any union data inside the Resource as the provided WorkspaceResource
func (t *Resource) FromWorkspaceResource(v WorkspaceResource) error {
	v.Kind = "WorkspaceResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWorkspaceResource performs a merge with any union data inside the Resource, using the provided WorkspaceResource
func (t *Resource) MergeWorkspaceResource(v WorkspaceResource) error {
	v.Kind = "WorkspaceResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPeerConfigResource returns the union data inside the Resource as a PeerConfigResource
func (t Resource) AsPeerConfigResource() (PeerConfigResource, error) {
	var body PeerConfigResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPeerConfigResource overwrites any union data inside the Resource as the provided PeerConfigResource
func (t *Resource) FromPeerConfigResource(v PeerConfigResource) error {
	v.Kind = "PeerConfigResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePeerConfigResource performs a merge with any union data inside the Resource, using the provided PeerConfigResource
func (t *Resource) MergePeerConfigResource(v PeerConfigResource) error {
	v.Kind = "PeerConfigResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResourceListResource returns the union data inside the Resource as a ResourceListResource
func (t Resource) AsResourceListResource() (ResourceListResource, error) {
	var body ResourceListResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResourceListResource overwrites any union data inside the Resource as the provided ResourceListResource
func (t *Resource) FromResourceListResource(v ResourceListResource) error {
	v.Kind = "ResourceListResource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResourceListResource performs a merge with any union data inside the Resource, using the provided ResourceListResource
func (t *Resource) MergeResourceListResource(v ResourceListResource) error {
	v.Kind = "ResourceListResource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Resource) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Resource) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "CredentialResource":
		return t.AsCredentialResource()
	case "MiniMaxTenantResource":
		return t.AsMiniMaxTenantResource()
	case "ModelResource":
		return t.AsModelResource()
	case "PeerConfigResource":
		return t.AsPeerConfigResource()
	case "ResourceListResource":
		return t.AsResourceListResource()
	case "VoiceResource":
		return t.AsVoiceResource()
	case "VolcTenantResource":
		return t.AsVolcTenantResource()
	case "WorkflowResource":
		return t.AsWorkflowResource()
	case "WorkspaceResource":
		return t.AsWorkspaceResource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Resource) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Resource) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
