// This file is auto-generated by @hey-api/openapi-ts

export { getServerInfo, type Options, registerGear } from './sdk.gen';
export type { ClientOptions, Configuration, DeviceInfo, ErrorPayload, ErrorResponse, FirmwareConfig, Gear, GearCertification, GearCertificationAuthority, GearCertificationType, GearFirmwareChannel, GearImei, GearLabel, GearRole, GearStatus, GetServerInfoData, GetServerInfoError, GetServerInfoErrors, GetServerInfoResponse, GetServerInfoResponses, HardwareInfo, RegisterGearData, RegisterGearError, RegisterGearErrors, RegisterGearResponse, RegisterGearResponses, Registration, RegistrationRequest, RegistrationResult, ServerInfo } from './types.gen';
