// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AdoptPeerPetData, AdoptPeerPetResponses, ClaimPeerRewardData, ClaimPeerRewardResponses, CreateWebRtcOfferData, CreateWebRtcOfferResponses, DeletePeerPetData, DeletePeerPetResponses, FeedPeerPetData, FeedPeerPetResponses, GetPeerPetData, GetPeerPetResponses, GetPeerRewardData, GetPeerRewardResponses, GetPeerWalletData, GetPeerWalletResponses, GetPeerWalletTransactionData, GetPeerWalletTransactionResponses, ListClientVoicesData, ListClientVoicesResponses, ListPeerCredentialsData, ListPeerCredentialsResponses, ListPeerModelsData, ListPeerModelsResponses, ListPeerPetsData, ListPeerPetsResponses, ListPeerResourceNamesData, ListPeerResourceNamesResponses, ListPeerRewardsData, ListPeerRewardsResponses, ListPeerVoicesData, ListPeerVoicesResponses, ListPeerWalletTransactionsData, ListPeerWalletTransactionsResponses, ListPeerWorkflowsData, ListPeerWorkflowsResponses, ListPeerWorkspacesData, ListPeerWorkspacesResponses, PlayWithPeerPetData, PlayWithPeerPetResponses, PutPeerPetData, PutPeerPetResponses, StreamPlayableVoicesData, StreamPlayableVoicesResponse, StreamPlayableVoicesResponses, WashPeerPetData, WashPeerPetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List resource names exposed to the current peer
 */
export const listPeerResourceNames = <ThrowOnError extends boolean = false>(options?: Options<ListPeerResourceNamesData, ThrowOnError>) => (options?.client ?? client).get<ListPeerResourceNamesResponses, unknown, ThrowOnError>({ url: '/peer-resources', ...options });

/**
 * List workspaces readable by the current peer
 */
export const listPeerWorkspaces = <ThrowOnError extends boolean = false>(options?: Options<ListPeerWorkspacesData, ThrowOnError>) => (options?.client ?? client).get<ListPeerWorkspacesResponses, unknown, ThrowOnError>({ url: '/peer-resources/workspaces', ...options });

/**
 * List workflows readable by the current peer
 */
export const listPeerWorkflows = <ThrowOnError extends boolean = false>(options?: Options<ListPeerWorkflowsData, ThrowOnError>) => (options?.client ?? client).get<ListPeerWorkflowsResponses, unknown, ThrowOnError>({ url: '/peer-resources/workflows', ...options });

/**
 * List models readable by the current peer
 */
export const listPeerModels = <ThrowOnError extends boolean = false>(options?: Options<ListPeerModelsData, ThrowOnError>) => (options?.client ?? client).get<ListPeerModelsResponses, unknown, ThrowOnError>({ url: '/peer-resources/models', ...options });

/**
 * List credentials readable by the current peer
 */
export const listPeerCredentials = <ThrowOnError extends boolean = false>(options?: Options<ListPeerCredentialsData, ThrowOnError>) => (options?.client ?? client).get<ListPeerCredentialsResponses, unknown, ThrowOnError>({ url: '/peer-resources/credentials', ...options });

/**
 * List voices readable by the current peer
 */
export const listPeerVoices = <ThrowOnError extends boolean = false>(options?: Options<ListPeerVoicesData, ThrowOnError>) => (options?.client ?? client).get<ListPeerVoicesResponses, unknown, ThrowOnError>({ url: '/peer-resources/voices', ...options });

/**
 * List pets owned by the current peer
 */
export const listPeerPets = <ThrowOnError extends boolean = false>(options?: Options<ListPeerPetsData, ThrowOnError>) => (options?.client ?? client).get<ListPeerPetsResponses, unknown, ThrowOnError>({ url: '/peer-resources/pets', ...options });

/**
 * Adopt a pet for the current peer
 */
export const adoptPeerPet = <ThrowOnError extends boolean = false>(options: Options<AdoptPeerPetData, ThrowOnError>) => (options.client ?? client).post<AdoptPeerPetResponses, unknown, ThrowOnError>({
    url: '/peer-resources/pets',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a pet owned by the current peer
 */
export const deletePeerPet = <ThrowOnError extends boolean = false>(options: Options<DeletePeerPetData, ThrowOnError>) => (options.client ?? client).delete<DeletePeerPetResponses, unknown, ThrowOnError>({ url: '/peer-resources/pets/{id}', ...options });

/**
 * Get a pet owned by the current peer
 */
export const getPeerPet = <ThrowOnError extends boolean = false>(options: Options<GetPeerPetData, ThrowOnError>) => (options.client ?? client).get<GetPeerPetResponses, unknown, ThrowOnError>({ url: '/peer-resources/pets/{id}', ...options });

/**
 * Update a pet owned by the current peer
 */
export const putPeerPet = <ThrowOnError extends boolean = false>(options: Options<PutPeerPetData, ThrowOnError>) => (options.client ?? client).put<PutPeerPetResponses, unknown, ThrowOnError>({
    url: '/peer-resources/pets/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Feed a pet owned by the current peer
 */
export const feedPeerPet = <ThrowOnError extends boolean = false>(options: Options<FeedPeerPetData, ThrowOnError>) => (options.client ?? client).post<FeedPeerPetResponses, unknown, ThrowOnError>({
    url: '/peer-resources/pets/{id}/@feed',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Wash a pet owned by the current peer
 */
export const washPeerPet = <ThrowOnError extends boolean = false>(options: Options<WashPeerPetData, ThrowOnError>) => (options.client ?? client).post<WashPeerPetResponses, unknown, ThrowOnError>({
    url: '/peer-resources/pets/{id}/@wash',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Play with a pet owned by the current peer
 */
export const playWithPeerPet = <ThrowOnError extends boolean = false>(options: Options<PlayWithPeerPetData, ThrowOnError>) => (options.client ?? client).post<PlayWithPeerPetResponses, unknown, ThrowOnError>({
    url: '/peer-resources/pets/{id}/@play',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get the current peer wallet
 */
export const getPeerWallet = <ThrowOnError extends boolean = false>(options?: Options<GetPeerWalletData, ThrowOnError>) => (options?.client ?? client).get<GetPeerWalletResponses, unknown, ThrowOnError>({ url: '/peer-resources/wallet', ...options });

/**
 * List wallet transactions for the current peer
 */
export const listPeerWalletTransactions = <ThrowOnError extends boolean = false>(options?: Options<ListPeerWalletTransactionsData, ThrowOnError>) => (options?.client ?? client).get<ListPeerWalletTransactionsResponses, unknown, ThrowOnError>({ url: '/peer-resources/wallet-transactions', ...options });

/**
 * Get a wallet transaction for the current peer
 */
export const getPeerWalletTransaction = <ThrowOnError extends boolean = false>(options: Options<GetPeerWalletTransactionData, ThrowOnError>) => (options.client ?? client).get<GetPeerWalletTransactionResponses, unknown, ThrowOnError>({ url: '/peer-resources/wallet-transactions/{id}', ...options });

/**
 * List rewards for the current peer
 */
export const listPeerRewards = <ThrowOnError extends boolean = false>(options?: Options<ListPeerRewardsData, ThrowOnError>) => (options?.client ?? client).get<ListPeerRewardsResponses, unknown, ThrowOnError>({ url: '/peer-resources/rewards', ...options });

/**
 * Get a reward for the current peer
 */
export const getPeerReward = <ThrowOnError extends boolean = false>(options: Options<GetPeerRewardData, ThrowOnError>) => (options.client ?? client).get<GetPeerRewardResponses, unknown, ThrowOnError>({ url: '/peer-resources/rewards/{id}', ...options });

/**
 * Claim a reward for the current peer
 */
export const claimPeerReward = <ThrowOnError extends boolean = false>(options: Options<ClaimPeerRewardData, ThrowOnError>) => (options.client ?? client).post<ClaimPeerRewardResponses, unknown, ThrowOnError>({
    url: '/peer-resources/rewards/@claim',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Stream playable voices as server-sent events
 */
export const streamPlayableVoices = <ThrowOnError extends boolean = false>(options?: Options<StreamPlayableVoicesData, ThrowOnError, StreamPlayableVoicesResponse>) => (options?.client ?? client).sse.get<StreamPlayableVoicesResponses, unknown, ThrowOnError>({ url: '/play/voices/stream', ...options });

/**
 * List OpenAI-compatible voices readable by the current peer
 */
export const listClientVoices = <ThrowOnError extends boolean = false>(options?: Options<ListClientVoicesData, ThrowOnError>) => (options?.client ?? client).get<ListClientVoicesResponses, unknown, ThrowOnError>({ url: '/v1/voices', ...options });

/**
 * Create a WebRTC answer for a browser offer
 */
export const createWebRtcOffer = <ThrowOnError extends boolean = false>(options: Options<CreateWebRtcOfferData, ThrowOnError>) => (options.client ?? client).post<CreateWebRtcOfferResponses, unknown, ThrowOnError>({
    url: '/webrtc/offer',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
