// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type PeerResourceName = 'workspaces' | 'workflows' | 'models' | 'credentials' | 'voices' | 'pets' | 'wallet' | 'wallet-transactions' | 'rewards';

export type PeerResourceNamesResponse = {
    resources: Array<PeerResourceName>;
};

export type ClientVoiceListResponse = {
    object: 'list';
    data: Array<Voice>;
    items?: Array<Voice>;
    has_next: boolean;
    next_cursor?: string;
};

export type PlayVoiceStreamEvent = {
    done?: boolean;
    error?: string;
    voice?: Voice;
};

export type WebRtcSessionDescription = {
    sdp: string;
    type: 'offer' | 'answer' | 'pranswer' | 'rollback';
};

export type CredentialListResponse = {
    items: Array<Credential>;
    has_next: boolean;
    next_cursor?: string;
};

export type ModelListResponse = {
    items: Array<Model>;
    has_next: boolean;
    next_cursor?: string;
};

export type PetAbilityStats = {
    level: number;
    exp: number;
    charm: number;
    intelligence: number;
    stamina: number;
    luck: number;
};

export type PetActionRequest = {
    pet_id: string;
    prompt: string;
};

export type PetAdoptRequest = {
    id?: string;
    name: string;
};

export type PetLifeStats = {
    satiety: number;
    cleanliness: number;
    mood: number;
    energy: number;
    health: number;
};

export type PetListResponse = {
    items: Array<PetObject>;
    has_next: boolean;
    next_cursor?: string;
};

export type PetObject = {
    id: string;
    name: string;
    species_id: string;
    voice_id: string;
    life: PetLifeStats;
    ability: PetAbilityStats;
    created_at: string;
    updated_at: string;
};

export type PetPutRequest = {
    id: string;
    name: string;
};

export type RewardClaimRequest = {
    prompt: string;
};

export type RewardListResponse = {
    items: Array<RewardObject>;
    has_next: boolean;
    next_cursor?: string;
};

export type RewardObject = {
    id: string;
    prompt: string;
    badge_id: string;
    point_amount: number;
    created_at: string;
};

export type WalletObject = {
    id: string;
    token_balance: number;
    point_balance: number;
    created_at: string;
    updated_at: string;
};

export type WalletTransactionObject = {
    id: string;
    token_delta: number;
    point_delta: number;
    reason: 'pet_adopt' | 'pet_feed' | 'pet_wash' | 'pet_play' | 'reward_claim';
    created_at: string;
};

export type WalletTransactionsListResponse = {
    items: Array<WalletTransactionObject>;
    has_next: boolean;
    next_cursor?: string;
};

export type WorkflowListResponse = {
    items: Array<FlowcraftWorkflow>;
    has_next: boolean;
    next_cursor?: string;
};

export type WorkspaceListResponse = {
    items: Array<Workspace>;
    has_next: boolean;
    next_cursor?: string;
};

export type Credential = {
    name: string;
    provider: string;
    method: CredentialMethod;
    body: CredentialBody;
    description?: string;
    created_at: string;
    updated_at: string;
};

export type CredentialBody = {
    [key: string]: unknown;
};

/**
 * Credential authentication method
 */
export type CredentialMethod = 'api_key' | 'token' | 'app_id_token';

export type Model = {
    id: string;
    kind: ModelKind;
    source: ModelSource;
    provider: ModelProvider;
    name?: string;
    description?: string;
    capabilities?: ModelCapabilities;
    provider_data?: ModelProviderData;
    synced_at?: string;
    created_at: string;
    updated_at: string;
};

export type ModelCapabilities = {
    json_output?: boolean;
    tool_calls?: boolean;
    text_only?: boolean;
    system_role?: boolean;
    temperature?: boolean;
    thinking?: ModelThinkingCapability;
};

export type ModelThinkingCapability = {
    supported: boolean;
    /**
     * Provider request parameter mapping, such as reasoning_effort, thinking.type, or enable_thinking.
     */
    param?: string;
    /**
     * Optional provider request parameter used for the selected thinking level or budget.
     */
    level_param?: string;
    levels?: Array<string>;
    default_level?: string;
};

/**
 * Runtime role of a model.
 */
export type ModelKind = 'llm' | 'tts' | 'asr' | 'embedding';

export type ModelProvider = {
    kind: ModelProviderKind;
    name: string;
};

/**
 * Provider-specific model runtime configuration keyed by provider kind.
 */
export type ModelProviderData = {
    [key: string]: unknown;
};

/**
 * Provider resource kind usable by model runtime.
 */
export type ModelProviderKind = 'gemini-tenant' | 'dashscope-tenant' | 'openai-tenant' | 'volc-tenant';

/**
 * How the model entered the global catalog
 */
export type ModelSource = 'sync' | 'manual';

export type Voice = {
    id: string;
    source: VoiceSource;
    provider: VoiceProvider;
    name?: string;
    description?: string;
    provider_data?: VoiceProviderData;
    synced_at?: string;
    created_at: string;
    updated_at: string;
};

export type VoiceProvider = {
    kind: VoiceProviderKind;
    name: string;
};

/**
 * Provider-specific voice runtime configuration keyed by provider kind.
 */
export type VoiceProviderData = {
    [key: string]: unknown;
};

/**
 * Provider resource kind usable by voice runtime.
 */
export type VoiceProviderKind = 'gemini-tenant' | 'dashscope-tenant' | 'openai-tenant' | 'minimax-tenant' | 'volc-tenant';

/**
 * How the voice entered the global catalog
 */
export type VoiceSource = 'sync' | 'manual';

export type WorkflowApiVersion = 'gizclaw.flowcraft/v1alpha1';

export type WorkflowMetadata = {
    name: string;
    description?: string;
};

export type FlowcraftWorkflow = {
    apiVersion: WorkflowApiVersion;
    kind: 'FlowcraftWorkflow';
    metadata: WorkflowMetadata;
    spec: FlowcraftWorkflowSpec;
};

export type FlowcraftWorkflowSpec = {
    [key: string]: unknown;
};

export type Workspace = {
    name: string;
    workflow_name: string;
    parameters?: {
        [key: string]: unknown;
    };
    created_at: string;
    updated_at: string;
};

export type Cursor = string;

export type Limit = number;

export type PetId = string;

export type RewardId = string;

export type WalletTransactionId = string;

export type VoiceSource2 = VoiceSource;

export type VoiceProviderKind2 = VoiceProviderKind;

export type VoiceProviderName = string;

export type ListPeerResourceNamesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/peer-resources';
};

export type ListPeerResourceNamesResponses = {
    /**
     * The available peer resource names.
     */
    200: PeerResourceNamesResponse;
};

export type ListPeerResourceNamesResponse = ListPeerResourceNamesResponses[keyof ListPeerResourceNamesResponses];

export type ListPeerWorkspacesData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/peer-resources/workspaces';
};

export type ListPeerWorkspacesResponses = {
    /**
     * A page of workspaces.
     */
    200: WorkspaceListResponse;
};

export type ListPeerWorkspacesResponse = ListPeerWorkspacesResponses[keyof ListPeerWorkspacesResponses];

export type ListPeerWorkflowsData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/peer-resources/workflows';
};

export type ListPeerWorkflowsResponses = {
    /**
     * A page of workflows.
     */
    200: WorkflowListResponse;
};

export type ListPeerWorkflowsResponse = ListPeerWorkflowsResponses[keyof ListPeerWorkflowsResponses];

export type ListPeerModelsData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/peer-resources/models';
};

export type ListPeerModelsResponses = {
    /**
     * A page of models.
     */
    200: ModelListResponse;
};

export type ListPeerModelsResponse = ListPeerModelsResponses[keyof ListPeerModelsResponses];

export type ListPeerCredentialsData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/peer-resources/credentials';
};

export type ListPeerCredentialsResponses = {
    /**
     * A page of sanitized credentials.
     */
    200: CredentialListResponse;
};

export type ListPeerCredentialsResponse = ListPeerCredentialsResponses[keyof ListPeerCredentialsResponses];

export type ListPeerVoicesData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
        source?: VoiceSource;
        provider_kind?: VoiceProviderKind;
        provider_name?: string;
    };
    url: '/peer-resources/voices';
};

export type ListPeerVoicesResponses = {
    /**
     * A page of voices.
     */
    200: ClientVoiceListResponse;
};

export type ListPeerVoicesResponse = ListPeerVoicesResponses[keyof ListPeerVoicesResponses];

export type ListPeerPetsData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/peer-resources/pets';
};

export type ListPeerPetsResponses = {
    /**
     * A page of pets.
     */
    200: PetListResponse;
};

export type ListPeerPetsResponse = ListPeerPetsResponses[keyof ListPeerPetsResponses];

export type AdoptPeerPetData = {
    body: PetAdoptRequest;
    path?: never;
    query?: never;
    url: '/peer-resources/pets';
};

export type AdoptPeerPetResponses = {
    /**
     * The adopted pet.
     */
    200: PetObject;
};

export type AdoptPeerPetResponse = AdoptPeerPetResponses[keyof AdoptPeerPetResponses];

export type DeletePeerPetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/peer-resources/pets/{id}';
};

export type DeletePeerPetResponses = {
    /**
     * The deleted pet.
     */
    200: PetObject;
};

export type DeletePeerPetResponse = DeletePeerPetResponses[keyof DeletePeerPetResponses];

export type GetPeerPetData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/peer-resources/pets/{id}';
};

export type GetPeerPetResponses = {
    /**
     * The pet.
     */
    200: PetObject;
};

export type GetPeerPetResponse = GetPeerPetResponses[keyof GetPeerPetResponses];

export type PutPeerPetData = {
    body: PetPutRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/peer-resources/pets/{id}';
};

export type PutPeerPetResponses = {
    /**
     * The updated pet.
     */
    200: PetObject;
};

export type PutPeerPetResponse = PutPeerPetResponses[keyof PutPeerPetResponses];

export type FeedPeerPetData = {
    body: PetActionRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/peer-resources/pets/{id}/@feed';
};

export type FeedPeerPetResponses = {
    /**
     * The pet after feeding.
     */
    200: PetObject;
};

export type FeedPeerPetResponse = FeedPeerPetResponses[keyof FeedPeerPetResponses];

export type WashPeerPetData = {
    body: PetActionRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/peer-resources/pets/{id}/@wash';
};

export type WashPeerPetResponses = {
    /**
     * The pet after washing.
     */
    200: PetObject;
};

export type WashPeerPetResponse = WashPeerPetResponses[keyof WashPeerPetResponses];

export type PlayWithPeerPetData = {
    body: PetActionRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/peer-resources/pets/{id}/@play';
};

export type PlayWithPeerPetResponses = {
    /**
     * The pet after playing.
     */
    200: PetObject;
};

export type PlayWithPeerPetResponse = PlayWithPeerPetResponses[keyof PlayWithPeerPetResponses];

export type GetPeerWalletData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/peer-resources/wallet';
};

export type GetPeerWalletResponses = {
    /**
     * The wallet for the current peer.
     */
    200: WalletObject;
};

export type GetPeerWalletResponse = GetPeerWalletResponses[keyof GetPeerWalletResponses];

export type ListPeerWalletTransactionsData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/peer-resources/wallet-transactions';
};

export type ListPeerWalletTransactionsResponses = {
    /**
     * A page of wallet transactions.
     */
    200: WalletTransactionsListResponse;
};

export type ListPeerWalletTransactionsResponse = ListPeerWalletTransactionsResponses[keyof ListPeerWalletTransactionsResponses];

export type GetPeerWalletTransactionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/peer-resources/wallet-transactions/{id}';
};

export type GetPeerWalletTransactionResponses = {
    /**
     * The wallet transaction.
     */
    200: WalletTransactionObject;
};

export type GetPeerWalletTransactionResponse = GetPeerWalletTransactionResponses[keyof GetPeerWalletTransactionResponses];

export type ListPeerRewardsData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/peer-resources/rewards';
};

export type ListPeerRewardsResponses = {
    /**
     * A page of rewards.
     */
    200: RewardListResponse;
};

export type ListPeerRewardsResponse = ListPeerRewardsResponses[keyof ListPeerRewardsResponses];

export type GetPeerRewardData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/peer-resources/rewards/{id}';
};

export type GetPeerRewardResponses = {
    /**
     * The reward.
     */
    200: RewardObject;
};

export type GetPeerRewardResponse = GetPeerRewardResponses[keyof GetPeerRewardResponses];

export type ClaimPeerRewardData = {
    body: RewardClaimRequest;
    path?: never;
    query?: never;
    url: '/peer-resources/rewards/@claim';
};

export type ClaimPeerRewardResponses = {
    /**
     * The claimed reward.
     */
    200: RewardObject;
};

export type ClaimPeerRewardResponse = ClaimPeerRewardResponses[keyof ClaimPeerRewardResponses];

export type StreamPlayableVoicesData = {
    body?: never;
    path?: never;
    query?: {
        provider_kind?: VoiceProviderKind;
        provider_name?: string;
        limit?: number;
    };
    url: '/play/voices/stream';
};

export type StreamPlayableVoicesResponses = {
    /**
     * Server-sent voice events. Each event data field is a PlayVoiceStreamEvent JSON object.
     */
    200: PlayVoiceStreamEvent;
};

export type StreamPlayableVoicesResponse = StreamPlayableVoicesResponses[keyof StreamPlayableVoicesResponses];

export type ListClientVoicesData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
        source?: VoiceSource;
        provider_kind?: VoiceProviderKind;
        provider_name?: string;
    };
    url: '/v1/voices';
};

export type ListClientVoicesResponses = {
    /**
     * A page of voices exposed through the local OpenAI-compatible proxy.
     */
    200: ClientVoiceListResponse;
};

export type ListClientVoicesResponse = ListClientVoicesResponses[keyof ListClientVoicesResponses];

export type CreateWebRtcOfferData = {
    body: WebRtcSessionDescription;
    path?: never;
    query?: never;
    url: '/webrtc/offer';
};

export type CreateWebRtcOfferResponses = {
    /**
     * A WebRTC answer.
     */
    200: WebRtcSessionDescription;
};

export type CreateWebRtcOfferResponse = CreateWebRtcOfferResponses[keyof CreateWebRtcOfferResponses];
