// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type LoginResult = {
    access_token: string;
    token_type: 'Bearer';
    expires_at: number;
};

export type ErrorPayload = {
    code: string;
    message: string;
    details?: {
        [key: string]: unknown;
    };
};

export type ErrorResponse = {
    error: ErrorPayload;
};

export type ServerInfo = {
    public_key: string;
    server_time: number;
    build_commit: string;
};

export type LoginData = {
    body?: never;
    headers: {
        'X-Public-Key': string;
        Authorization: string;
    };
    path?: never;
    query?: never;
    url: '/login';
};

export type LoginErrors = {
    /**
     * Invalid assertion
     */
    401: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Login result
     */
    200: LoginResult;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetServerInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/server-info';
};

export type GetServerInfoErrors = {
    /**
     * Invalid params
     */
    400: ErrorResponse;
};

export type GetServerInfoError = GetServerInfoErrors[keyof GetServerInfoErrors];

export type GetServerInfoResponses = {
    /**
     * Server info
     */
    200: ServerInfo;
};

export type GetServerInfoResponse = GetServerInfoResponses[keyof GetServerInfoResponses];
